name: IronFlow
description: "Strength training and fitness app for mobile devices."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.12.2+60

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # app info
  package_info_plus: ^8.1.2
  
  # calendar
  table_calendar: ^3.0.0

  # storage
  sqflite: ^2.0.0+4
  path: ^1.8.0
  path_provider: ^2.1.5
  file_picker: ^8.1.7

  # high score stuff
  confetti: ^0.6.0

  # permissions android
  permission_handler: ^11.3.1

  # visualization
  fl_chart: ^0.68.0

  # settings (to remember user settings)
  shared_preferences: ^2.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # logging framework
  logging: ^1.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # tests
  test: ^1.17.0
  mockito: ^5.0.16

  # code formatting/linting
  flutter_lints: ^3.0.0

  # icon
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/wave_app_icon.png"
  adaptive_icon_foreground: "assets/icon/wave_app_icon_transparent_padded.png"
  adaptive_icon_background: "assets/icon/background_image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/wave_app_icon_transparent_thumbnail.png