name: Build IPA

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Build app
        run: |
          cd ./
          flutter pub get
          flutter build ipa --release --verbose --no-codesign
      
      - name: Create IPA
        run: |
          mkdir payload/
          mv build/ios/iphoneos/Runner.app/ payload
          zip -qq -r -9 app-release.ipa payload
      
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: ./build/ios/ipa/app-release.ipa
          if-no-files-found: error
