name: Build APK

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Build APK
        run: |
          cd sw_app/
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: sw_app/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
