name: Create Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    tags:
      - '*'
  release:
    types: [ published ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Configure build
        run: flutter clean && flutter pub get
      
      - name: Build APK
        env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: base64 -d <<< $KEY_JKS > ./android/app/release-key.jks && flutter build apk --release -v

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: ./build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
    
      - name: Upload APK to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.CI_TOKEN }}
          file: ./build/app/outputs/flutter-apk/app-release.apk
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true

  build-ipa:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          architecture: x64

      - name: Build iOS
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
      
      - name: Create IPA
        run: |
          mkdir ./Payload/
          mv ./build/ios/iphoneos/Runner.app/ ./Payload
          zip -qq -r -9 ./IronFlow.zip ./Payload
          mv IronFlow.zip IronFlow.ipa
      
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: ./IronFlow.ipa
          if-no-files-found: error
    
      - name: Upload IPA to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.CI_TOKEN }}
          file: ./IronFlow.ipa
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
