name: Integration Tests

on:
  pull_request:
    branches:
      - "*"
    paths:
      - lib/**
      - test/flows/**
      - '.github/workflows/integration_tests.yml'
  workflow_dispatch:

jobs:
  ios_e2e:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
     
      - name: Configure flutter
        run: flutter clean && flutter pub get

      - name: Installing maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Installing maestro dependencies
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
        
      - name: Launch iOS simulator
        run: xcrun simctl boot "iPhone 15 Pro Max"
      
      - name: Build iOS
        run: |
          xcrun xcodebuild \
            -scheme "Runner" \
            -workspace "ios/Runner.xcworkspace" \
            -configuration "Debug" \
            -sdk "iphonesimulator" \
            -destination "generic/platform=iOS Simulator"
      
      - name: Install app on simulator
        run: xcrun simctl install booted ./build/ios/iphonesimulator/Runner.app
      
      - name: Running tests with maestro
        run: $HOME/.maestro/bin/maestro test .maestro/ --format junit
