name: Integration tests

on:
  pull_request:
    branches:
      - "*"
    paths:
      - lib/**
      - test/flows/**
      - '.github/workflows/integration_tests.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
     
      - name: Configure flutter
        run: flutter clean && flutter pub get
      
      - name: Configure iPhone simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14 Pro'
      
      - name: Run integration tests
        uses: dniHze/maestro-test-action@v1
        with:
          flow: .maestro
          report: report.xml
