name: Integration Tests

on:
  pull_request:
    branches:
      - "*"
    paths:
      - lib/**
      - test/flows/**
      - '.github/workflows/integration_tests.yml'
  workflow_dispatch:

jobs:
  ios_e2e:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
     
      - name: Configure flutter
        run: flutter clean && flutter pub get

      - name: Installing maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash # will use `MAESTRO_VERSION` from env

      - name: Installing maestro dependencies
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
        
      - name: Launch iOS simulator
        run: xcrun simctl boot "iPhone 14 Pro"
      
      - name: Build flutter iOS app
        run: flutter build ios
      
      - name: Install app on simulator
        run: xcrun simctl install booted ./build/ios/iphoneos/Runner.app
      
      - name: Running tests with maestro
        run: $HOME/.maestro/bin/maestro test .maestro/ --format junit
      
      #- name: Configure maestro testing
      #  uses: dniHze/maestro-test-action@v1
      
      #- name: Run Android integration tests
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    arch: x86_64
      #    ram-size: 2048M
      #    target: default
      #    script: maestro test --format=junit --output=report.xml --no-ansi .maestro/
      
      #- name: Configure iPhone simulator
      #  uses: futureware-tech/simulator-action@v2
      #  with:
      #    model: 'iPhone 14 Pro'
      
      #- name: Run integration tests
      #  uses: dniHze/maestro-test-action@v1
      #  with:
      #    flow: .maestro
      #    report: report.xml
