name: Issue Labeler

on:
  #issues:
  #  types: [opened, edited]
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Label issue
        uses: github/issue-labeler@v3.3
        with:
          configuration-path: .github/actions/labeler.yml
          not-before: 2024-01-01T02:54:32Z
          enable-versioned-regex: 0
          include-title: 1
          include-body: 0
          repo-token: ${{ github.token }}
