name: Issue Assigner

on:
  #issues:
  #  types: [opened, edited]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Assign issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./\.github/scripts/auto-assignment.js')
            script({github, context})
